/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import example.model.DefaultNameAndDescriptionAndComments;
import example.model.NameAndDescriptionAndComments;

public class App {

    public static void main(String[] args) {
        NameAndDescriptionAndComments target =
                DefaultNameAndDescriptionAndComments.builder()
                        .name("world")
                        .addComment("hello")
                        .build();
        System.out.println("Hello " + target);
    }




}
